version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - photobox-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/photobox
    networks:
      - photobox-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: photobox
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - photobox-network

networks:
  photobox-network:

volumes:
  db_data:
